/**
 * `@workspace/api-zod` — Zod-based runtime validators for the OpenAPI spec.
 *
 * Re-exports the zod schemas (one per request/response shape) generated by
 * orval from `lib/api-spec/openapi.yaml`. Consumers infer the matching
 * TypeScript types via `z.infer<typeof Schema>` rather than importing
 * separate TS interfaces — single source of truth, zero duplicate-name
 * collisions.
 *
 * `indexFiles: false` is set on the zod orval target precisely so this
 * file is preserved across `orval` runs.
 */
export * from "./generated/api";
