/**
 * Ollama library — broad discovery list for power-user mode (Task #64).
 *
 * Distinct from `MODEL_CATALOGUE`:
 *  - `MODEL_CATALOGUE` is the small, curated set the recommendation engine
 *    chooses from. Adding an entry there means it can be auto-recommended
 *    to a user on first run.
 *  - `OLLAMA_LIBRARY` is the broader Ollama-published library exposed to
 *    power users who want to step outside the curated set. Entries here
 *    are NOT considered by the recommendation engine — they only appear
 *    in the "Power user: see all models" disclosure with a "Fits" /
 *    "Needs more RAM" annotation computed against the host.
 *
 * Sizing comes from the Ollama registry's published Q4 quant sizes;
 * `ramRequiredBytes` adds the typical KV-cache + activation overhead
 * (~1.2-1.4× the model size, rounded). These are honest estimates, not
 * runtime measurements — the fit annotation is "will it physically load"
 * not "will it be fast".
 */
import type { ModelCatalogueEntry } from "@workspace/types";

const ONE_GB = 1024 * 1024 * 1024;
const gb = (n: number): number => Math.round(n * ONE_GB);

export const OLLAMA_LIBRARY: ReadonlyArray<ModelCatalogueEntry> = [
  // ─── Llama family ─────────────────────────────────────────────────
  {
    id: "llama3.2:1b",
    displayName: "Llama 3.2 1B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(1.3),
    ramRequiredBytes: gb(2),
    minTier: "low",
    capabilities: ["general", "agent"],
    tradeoff: "Tiny — fits anywhere. Best for quick tools, weak on reasoning.",
  },
  {
    id: "llama3.2:3b",
    displayName: "Llama 3.2 3B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(2),
    ramRequiredBytes: gb(3),
    minTier: "low",
    capabilities: ["general", "agent", "writing"],
    tradeoff: "Small + capable. Good fallback when 7B+ doesn't fit.",
  },
  {
    id: "llama3.1:8b",
    displayName: "Llama 3.1 8B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(4.7),
    ramRequiredBytes: gb(6),
    minTier: "high",
    capabilities: ["writing", "code", "agent", "general", "reasoning"],
    tradeoff: "Strong all-rounder for 16GB hosts.",
  },
  {
    id: "llama3.2:13b",
    displayName: "Llama 3.2 13B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(8.1),
    ramRequiredBytes: gb(10),
    minTier: "high",
    capabilities: ["writing", "code", "agent", "general", "reasoning"],
    tradeoff: "Strong mid-range — great for 16–18 GB Apple Silicon hosts.",
  },
  {
    id: "llama3.1:32b",
    displayName: "Llama 3.1 32B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(20),
    ramRequiredBytes: gb(24),
    minTier: "pro",
    capabilities: ["writing", "code", "agent", "general", "reasoning"],
    tradeoff: "Near GPT-3.5 quality on 32 GB Apple Silicon M2 Pro/Max or M3 Pro.",
  },
  {
    id: "llama3.1:70b",
    displayName: "Llama 3.1 70B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(40),
    ramRequiredBytes: gb(44),
    minTier: "pro",
    capabilities: ["writing", "code", "agent", "general", "reasoning"],
    tradeoff: "Near GPT-4 quality — requires 64 GB+ unified memory (M3 Max / Ultra).",
  },
  {
    id: "llama3.3:70b",
    displayName: "Llama 3.3 70B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(43),
    ramRequiredBytes: gb(45),
    minTier: "pro",
    capabilities: ["writing", "code", "agent", "general", "reasoning"],
    tradeoff: "Top-tier local quality. Workstation-class hardware required.",
  },
  // ─── Qwen family ──────────────────────────────────────────────────
  {
    id: "qwen2.5:0.5b",
    displayName: "Qwen 2.5 0.5B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(0.4),
    ramRequiredBytes: gb(1),
    minTier: "low",
    capabilities: ["general"],
    tradeoff: "Smallest practical model. Fast, but weak on long context.",
  },
  {
    id: "qwen2.5:3b",
    displayName: "Qwen 2.5 3B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(1.9),
    ramRequiredBytes: gb(2.5),
    minTier: "low",
    capabilities: ["general", "writing"],
    tradeoff: "Solid quality at a tiny footprint.",
  },
  {
    id: "qwen2.5:7b",
    displayName: "Qwen 2.5 7B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(4.7),
    ramRequiredBytes: gb(6),
    minTier: "mid",
    capabilities: ["writing", "general", "reasoning"],
    tradeoff: "Strong writing + multilingual. A natural Mistral 7B alternative.",
  },
  {
    id: "qwen2.5:14b",
    displayName: "Qwen 2.5 14B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(9),
    ramRequiredBytes: gb(11),
    minTier: "high",
    capabilities: ["writing", "general", "reasoning"],
    tradeoff: "Step up from 7B for nuanced writing on 16GB+ hosts.",
  },
  {
    id: "qwen2.5:32b",
    displayName: "Qwen 2.5 32B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(20),
    ramRequiredBytes: gb(22),
    minTier: "pro",
    capabilities: ["writing", "reasoning", "general"],
    tradeoff: "Frontier-class reasoning. Needs 32GB+ headroom.",
  },
  {
    id: "qwen2.5:72b",
    displayName: "Qwen 2.5 72B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(47),
    ramRequiredBytes: gb(50),
    minTier: "pro",
    capabilities: ["writing", "reasoning", "general"],
    tradeoff: "Highest Qwen quality — workstation territory.",
  },
  {
    id: "qwen2.5-coder:1.5b",
    displayName: "Qwen 2.5 Coder 1.5B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(1),
    ramRequiredBytes: gb(2),
    minTier: "low",
    capabilities: ["code"],
    tradeoff: "Tiny coding companion for very lean machines.",
  },
  {
    id: "qwen2.5-coder:14b",
    displayName: "Qwen 2.5 Coder 14B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(9),
    ramRequiredBytes: gb(11),
    minTier: "high",
    capabilities: ["code", "reasoning"],
    tradeoff: "Stronger refactor + tool-use than the 7B for 16GB+ hosts.",
  },
  {
    id: "qwen2.5-coder:32b",
    displayName: "Qwen 2.5 Coder 32B",
    family: "qwen",
    role: "primary",
    sizeBytes: gb(20),
    ramRequiredBytes: gb(22),
    minTier: "pro",
    capabilities: ["code", "reasoning"],
    tradeoff: "State of the art local code model. Pro tier only.",
  },
  // ─── Mistral family ───────────────────────────────────────────────
  {
    id: "mistral-nemo:12b",
    displayName: "Mistral Nemo 12B",
    family: "mistral",
    role: "primary",
    sizeBytes: gb(7.1),
    ramRequiredBytes: gb(9),
    minTier: "high",
    capabilities: ["writing", "general"],
    tradeoff: "128k context window. Great for long-form writing.",
  },
  {
    id: "mixtral:8x7b",
    displayName: "Mixtral 8x7B (MoE)",
    family: "mistral",
    role: "primary",
    sizeBytes: gb(26),
    ramRequiredBytes: gb(30),
    minTier: "pro",
    capabilities: ["writing", "code", "reasoning", "general"],
    tradeoff: "Mixture of experts — high quality at MoE sparsity tradeoffs.",
  },
  // ─── Gemma family ─────────────────────────────────────────────────
  {
    id: "gemma2:2b",
    displayName: "Gemma 2 2B",
    family: "gemma",
    role: "primary",
    sizeBytes: gb(1.6),
    ramRequiredBytes: gb(2.5),
    minTier: "low",
    capabilities: ["general", "writing"],
    tradeoff: "Google's small Gemma — efficient for chat on lean hosts.",
  },
  {
    id: "gemma2:9b",
    displayName: "Gemma 2 9B",
    family: "gemma",
    role: "primary",
    sizeBytes: gb(5.4),
    ramRequiredBytes: gb(7),
    minTier: "mid",
    capabilities: ["writing", "general"],
    tradeoff: "Strong instruction-following at the 8B-class footprint.",
  },
  {
    id: "gemma2:27b",
    displayName: "Gemma 2 27B",
    family: "gemma",
    role: "primary",
    sizeBytes: gb(16),
    ramRequiredBytes: gb(18),
    minTier: "high",
    capabilities: ["writing", "reasoning", "general"],
    tradeoff: "Best Gemma quality — 32GB+ recommended.",
  },
  // ─── Phi family ───────────────────────────────────────────────────
  {
    id: "phi3:medium",
    displayName: "Phi-3 Medium (14B)",
    family: "phi",
    role: "primary",
    sizeBytes: gb(7.9),
    ramRequiredBytes: gb(10),
    minTier: "high",
    capabilities: ["writing", "reasoning"],
    tradeoff: "Microsoft's reasoning-tuned medium model.",
  },
  // ─── DeepSeek family ──────────────────────────────────────────────
  {
    id: "deepseek-coder-v2:16b",
    displayName: "DeepSeek Coder v2 16B (MoE)",
    family: "deepseek",
    role: "primary",
    sizeBytes: gb(9.1),
    ramRequiredBytes: gb(11),
    minTier: "high",
    capabilities: ["code", "reasoning"],
    tradeoff: "Sparse MoE — strong coding at moderate active params.",
  },
  {
    id: "deepseek-r1:7b",
    displayName: "DeepSeek R1 7B",
    family: "deepseek",
    role: "primary",
    sizeBytes: gb(4.7),
    ramRequiredBytes: gb(6),
    minTier: "mid",
    capabilities: ["reasoning", "general"],
    tradeoff: "Reasoning-distilled R1. Great chain-of-thought for the size.",
  },
  {
    id: "deepseek-r1:14b",
    displayName: "DeepSeek R1 14B",
    family: "deepseek",
    role: "primary",
    sizeBytes: gb(9),
    ramRequiredBytes: gb(11),
    minTier: "high",
    capabilities: ["reasoning", "general"],
    tradeoff: "Stronger reasoning than the 7B distill.",
  },
  {
    id: "deepseek-r1:32b",
    displayName: "DeepSeek R1 32B",
    family: "deepseek",
    role: "primary",
    sizeBytes: gb(20),
    ramRequiredBytes: gb(22),
    minTier: "pro",
    capabilities: ["reasoning", "general"],
    tradeoff: "Frontier reasoning at 32GB+ hosts.",
  },
  {
    id: "deepseek-r1:70b",
    displayName: "DeepSeek R1 70B",
    family: "deepseek",
    role: "primary",
    sizeBytes: gb(43),
    ramRequiredBytes: gb(45),
    minTier: "pro",
    capabilities: ["reasoning", "general"],
    tradeoff: "Top reasoning quality. Workstation hardware required.",
  },
  // ─── CodeLlama family ─────────────────────────────────────────────
  {
    id: "codellama:7b",
    displayName: "CodeLlama 7B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(3.8),
    ramRequiredBytes: gb(5),
    minTier: "mid",
    capabilities: ["code"],
    tradeoff: "Classic code-tuned Llama 2. Older but well-known.",
  },
  {
    id: "codellama:13b",
    displayName: "CodeLlama 13B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(7.4),
    ramRequiredBytes: gb(9),
    minTier: "high",
    capabilities: ["code"],
    tradeoff: "Step up for 16GB hosts wanting Llama-2-era coding.",
  },
  {
    id: "codellama:34b",
    displayName: "CodeLlama 34B",
    family: "llama",
    role: "primary",
    sizeBytes: gb(19),
    ramRequiredBytes: gb(22),
    minTier: "pro",
    capabilities: ["code"],
    tradeoff: "Largest open CodeLlama. 32GB+ host recommended.",
  },
  // ─── Embedding models ─────────────────────────────────────────────
  {
    id: "nomic-embed-text",
    displayName: "Nomic Embed Text",
    family: "nomic",
    role: "vision",
    sizeBytes: Math.round(0.274 * ONE_GB),
    ramRequiredBytes: Math.round(0.4 * ONE_GB),
    minTier: "low",
    capabilities: ["general"],
    tradeoff:
      "Small text-embedding model (~274 MB) used for knowledge-base vector search (RAG).",
  },
  // ─── Vision / multimodal ──────────────────────────────────────────
  {
    id: "llava:7b",
    displayName: "LLaVA 7B (Vision)",
    family: "llava",
    role: "vision",
    sizeBytes: gb(4.7),
    ramRequiredBytes: gb(6),
    minTier: "mid",
    capabilities: ["vision"],
    tradeoff:
      "Larger vision model — replaces Moondream when you want richer image reasoning.",
  },
  {
    id: "llava:13b",
    displayName: "LLaVA 13B (Vision)",
    family: "llava",
    role: "vision",
    sizeBytes: gb(8),
    ramRequiredBytes: gb(10),
    minTier: "high",
    capabilities: ["vision"],
    tradeoff: "Better visual reasoning. Heavy compared to Moondream's 1.6GB.",
  },
];
