/**
 * `pairing_tokens` — short-lived QR pairing codes generated by the desktop
 * OP and consumed by the Mobile Companion PWA on the phone.
 *
 * The `code` column is the human-pronounceable code embedded in the QR
 * payload. After the PWA claims the code we mark `claimedAt` and write
 * the resulting `paired_devices` row id into `deviceId` so we have a full
 * audit trail of which phone consumed which code.
 */
import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

import { tenants } from "./tenants";
import { workspaces } from "./workspaces";

export const pairingTokens = sqliteTable(
  "pairing_tokens",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull().references(() => tenants.id),
    workspaceId: text("workspace_id").notNull().references(() => workspaces.id),
    /** The short pairing code embedded in the QR payload. Unique per tenant. */
    code: text("code").notNull(),
    /** Hash of the relay token returned to the PWA upon successful claim. */
    relayTokenHash: text("relay_token_hash").notNull(),
    expiresAt: integer("expires_at").notNull(),
    claimedAt: integer("claimed_at"),
    deviceId: text("device_id"),
    createdAt: integer("created_at").notNull().default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at").notNull().default(sql`(unixepoch() * 1000)`),
    version: integer("version").notNull().default(1),
  },
  (t) => ({
    tenantIdx: index("idx_pairing_tokens_tenant").on(t.tenantId),
    workspaceIdx: index("idx_pairing_tokens_workspace").on(t.workspaceId),
    codeIdx: index("idx_pairing_tokens_code").on(t.tenantId, t.code),
    expiresIdx: index("idx_pairing_tokens_expires").on(t.expiresAt),
  }),
);

export type PairingToken = typeof pairingTokens.$inferSelect;
export type NewPairingToken = typeof pairingTokens.$inferInsert;
