/**
 * `voip_calls` — VoIP call records (placed via Twilio, received on the
 * dedicated OP number).
 *
 * `direction` is `outbound` for OP-placed calls and `inbound` for received
 * calls. Whisper transcription is stored inline in `transcript`; the
 * recording path is local (Section 12 of the project context — recordings
 * never leave the box). The post-call summary is generated by the local
 * LLM after the call completes.
 */
import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

import { commAccounts } from "./comm-accounts";
import { contacts } from "./contacts";
import { tenants } from "./tenants";
import { workspaces } from "./workspaces";

export const voipCalls = sqliteTable(
  "voip_calls",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull().references(() => tenants.id),
    workspaceId: text("workspace_id").notNull().references(() => workspaces.id),
    accountId: text("account_id").notNull().references(() => commAccounts.id),
    contactId: text("contact_id").references(() => contacts.id),
    /** Provider call id (Twilio `CallSid`). */
    providerCallId: text("provider_call_id"),
    /** "inbound" | "outbound". */
    direction: text("direction").notNull(),
    fromNumber: text("from_number").notNull(),
    toNumber: text("to_number").notNull(),
    /** "queued" | "ringing" | "in_progress" | "completed" | "failed" | "no_answer". */
    status: text("status").notNull().default("queued"),
    durationSeconds: integer("duration_seconds"),
    transcript: text("transcript"),
    summary: text("summary"),
    /** Local filesystem path to the recording (never a URL). */
    recordingPath: text("recording_path"),
    startedAt: integer("started_at"),
    completedAt: integer("completed_at"),
    createdAt: integer("created_at").notNull().default(sql`(unixepoch() * 1000)`),
    updatedAt: integer("updated_at").notNull().default(sql`(unixepoch() * 1000)`),
    version: integer("version").notNull().default(1),
  },
  (t) => ({
    tenantIdx: index("idx_voip_calls_tenant").on(t.tenantId),
    workspaceIdx: index("idx_voip_calls_workspace").on(t.workspaceId),
    accountIdx: index("idx_voip_calls_account").on(t.accountId),
    contactIdx: index("idx_voip_calls_contact").on(t.contactId),
    statusIdx: index("idx_voip_calls_status").on(t.tenantId, t.status),
    startedIdx: index("idx_voip_calls_started").on(t.tenantId, t.startedAt),
  }),
);

export type VoipCall = typeof voipCalls.$inferSelect;
export type NewVoipCall = typeof voipCalls.$inferInsert;
